- hosts: tomcat
  become: true
  vars:
    tomcat_version: 9.0.41
    
    tomcat_permissions_production: True
    
    tomcat_users:
      - username: "tomcat"
        password: "1"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "tomcat2"
        password: "1"
        roles: "tomcat"        
  roles:
    - role: zaxos.tomcat-ansible-role
